### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Hans-Zwiesel** [svrooij/evohome#9]
Hi,
please, can you help me?
I am not able to start your example

1.) Installation
   you wrote: npn install @svrooij/evohome --save 
   I installed:  npm install @svrooij/evohome --save 

2.) ioBroker
    in JS Instance i add an additional NPM module: @svrooij/evohome

3.) ioBroker Script
    const EvohomeClient = require('../lib/evohome-client').EvohomeClient
    causes this error:
    javascript.0 | 2021-03-16 10:37:34.546 | error | (16230)  script.js.evohome.evohome_test: Error: Cannot find module        '/opt/iobroker/node_modules/iobroker.javascript/lib/../../../lib/evohome-client'

4.) evohome was installed at /root/node_modules/@svrooij
     and not in                       /opt/iobroker/node_modules/iobroker.javascript/node_modules

Please, can you help me?
many thanks,
regards
Hans

**Comment by svrooij** [comment]
This package is not meant to be used separate. It is just a library that should make it more easy to connect to an evohome api.

I'm using this package in [evohome2mqtt](https://github.com/svrooij/evohome2mqtt) that should give you some pointers on how to use a package.

If you start a new app (for iobroker) you will need to add a package.json file for your new application. Then install this package `npm i --save @svrooij/evohome` and then you can access it like here https://github.com/svrooij/evohome2mqtt/blob/97abb5344a07a8cfcdabb9c13d3102861c4d1aa2/src/bridge.js#L4
